src/controller/pathways-station-controller.ts, user-management-spec.json
Swagger documentation correction.
=> documentation correction

user-management-spec.json
=> swagger document correction

README.md, src/environment/environment.ts
Environment variables cleaned up
- README.md is updated with the correct application environment variables
- minor clean up of APP_PORT to PORT to be consistent with the remaining applications
=> env variables cleaned

user-management-spec.json
=> Schema correction

user-management-spec.json
specification updates for GET calls to return array of objects
=> specification updates

src/scripts/master-data.sql
Adding script to assign keycloak admin user 'admin' role to tdei system
=> admin role script

src/assets/user-management-spec.json, src/controller/user-management-controller.ts, src/model/dto/service-dto.ts, src/model/params/service-get-query-params.ts, src/scripts/init.sql, src/scripts/patches/1.0/service-type-changes.sql, src/service/flex-service.ts, test/unit/flex.service.test.ts
Added service_type for SERVICE GET/POST operations
unit test cases passed
=> service type change

src/model/dto/service-dto.ts, src/model/params/service-get-query-params.ts
=> service_type POST GET

src/assets/user-management-spec.json, src/exceptions/http/http-exceptions.ts, src/scripts/init.sql
Bug fix
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/944/
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/943/
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/952/
=> schema fix

src/assets/user-management-spec.json, src/model/params/service-get-query-params.ts
task
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/950/
=> enabling all option for services

src/assets/user-management-spec.json
Fixing the typo in existing required field related to below issue 
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/944/
=> required field correction

src/model/dto/project-group-dto.ts, src/model/dto/service-dto.ts
Bug fix for 
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/943/
=> Optional Phone

.github/workflows/production_workflow.yaml, README.md, db-management/migrations/20240731050530-poc-desc-upd.js, db-management/migrations/sqls/20240731050530-poc-desc-upd-down.sql, db-management/migrations/sqls/20240731050530-poc-desc-upd-up.sql
1. Prod workflow changes
2. Column description changes
=> Prod workflow

db-management/migrations/sqls/20240430101231-init-up.sql
SQL table column naming issue with id to permission_id
=> column issue

db-management/migrations/20240807095858-default-pg.js, db-management/migrations/sqls/20240807095858-default-pg-down.sql, db-management/migrations/sqls/20240807095858-default-pg-up.sql, src/app.ts, src/assets/user-management-spec.json, src/constants/role-constants.ts, src/controller/user-management-controller.ts, src/environment/environment.ts, src/model/dto/reset-credentials-dto.ts, src/service/interface/user-management-interface.ts, src/service/project-group-service.ts, src/service/user-management-service.ts, test/controller/user-management.controller.test.ts, test/unit/project-group.service.test.ts, test/unit/user-management.service.test.ts
Task 
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1120/
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1146/
Reset Credentials
1. User can reset their own credentials 
2. Admin can reset credentials of TDEI users
Default PG
1. On new user registration default roles and project group will be assigned.
2. Default project group cannot be made inactive.  
3. Default pg cannot be renamed.  
4. Get roles endpoint will not display system roles like admin, default as they are managed by system. 
5. Update permission cannot remove default role from any user.
=> Reset creds and Default pg changes

src/assets/user-management-spec.json
specification correction , userid to username change
=> specification correction

.github/workflows/dev_workflow.yaml, db-management/migrations/sqls/20240807095858-default-pg-up.sql, src/constants/role-constants.ts
1. Added workflow step to trigger user management client code. 
2. Changed the 'Default' pg group name to 'TDEI Default' as requested.
=> api client trigger + name change for default pg group

src/service/user-management-service.ts
Task : https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1243/
Handling email not verified exception
=> Verify email check

src/app.ts
bug fix 1262
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1262
=> bug fix 1262

src/app.ts, src/service/user-management-service.ts
Bug :
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/926
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1315
=> bug fix 1315,926

db-management/migrations/20241023141238-db-cleanup.js, db-management/migrations/sqls/20241023141238-db-cleanup-down.sql, db-management/migrations/sqls/20241023141238-db-cleanup-up.sql, src/assets/user-management-spec.json, src/controller/flex-service-controller.ts, src/controller/project-group-controller.ts, src/middleware/query-params-validation-middleware.ts, src/model/dto/login-dto.ts, src/model/dto/project-group-dto.ts, src/model/dto/register-user-dto.ts, src/model/dto/roles-req-dto.ts, src/model/dto/service-dto.ts, src/model/dto/service-update-dto.ts, src/model/params/project-group-get-query-params.ts, src/model/params/project-group-user-query-params.ts, src/model/params/service-get-query-params.ts, src/model/validators/polygon-validator.ts, src/service/flex-service.ts, src/service/interface/flex-service-interface.ts, src/service/interface/project-group-interface.ts, src/service/project-group-service.ts, src/service/user-management-service.ts, src/utility/utility.ts, test/unit/flex.service.test.ts, test/unit/project-group.service.test.ts
Task: https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1223/ 
User management service enhanced with 
- 400/404 cases 
- DB column length altered to 255 max chars for consistency across keycloak and TDEI systems. 
- Model validations on api requests to check input constraints
=> api feedback changes

db-management/migrations/20241023141238-db-cleanup.js, db-management/migrations/sqls/20241023141238-db-cleanup-down.sql, db-management/migrations/sqls/20241023141238-db-cleanup-up.sql, src/app.ts, src/assets/user-management-spec.json, src/controller/flex-service-controller.ts, src/controller/project-group-controller.ts, src/middleware/query-params-validation-middleware.ts, src/model/dto/login-dto.ts, src/model/dto/project-group-dto.ts, src/model/dto/register-user-dto.ts, src/model/dto/roles-req-dto.ts, src/model/dto/service-dto.ts, src/model/dto/service-update-dto.ts, src/model/params/project-group-get-query-params.ts, src/model/params/project-group-user-query-params.ts, src/model/params/service-get-query-params.ts, src/model/validators/polygon-validator.ts, src/service/flex-service.ts, src/service/interface/flex-service-interface.ts, src/service/interface/project-group-interface.ts, src/service/project-group-service.ts, src/service/user-management-service.ts, src/utility/utility.ts, test/unit/flex.service.test.ts, test/unit/project-group.service.test.ts
=> Dev to stage

package.json, src/model/validators/polygon-validator.ts
Issue - https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1413/
Project Group & Service multipolygon support
=> Project Group & Service multipolygon support

db-management/migrations/20241118114058-service-multipolygon.js, db-management/migrations/sqls/20241118114058-service-multipolygon-down.sql, db-management/migrations/sqls/20241118114058-service-multipolygon-up.sql
Task: https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1413/
Changing service and project_group table from Specific polygon geometry to Generic Geometry type to accept multipolygon
=> alter column to generic geometry

src/assets/user-management-spec.json, src/controller/flex-service-controller.ts, src/controller/project-group-controller.ts, src/exceptions/http/http-exceptions.ts, src/middleware/list-request-validation-middleware.ts, src/model/dto/service-update-dto.ts, src/model/params/project-group-get-query-params.ts, src/model/params/service-get-query-params.ts, src/service/flex-service.ts, src/service/project-group-service.ts, test/unit/flex.service.test.ts, test/unit/project-group.service.test.ts
Task: 
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1465/
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1501/
- Service & project group list api enabled with show_inactive flag which will list only inactive services
- Check to not allow editing service & project group in inactive status
- updated swagger documentation
- Changes Delete HTTP verb for deactive service & project group to PUT HTTP verb
=> Page size handling & Service/PG list inactive

src/exceptions/http/http-exceptions.ts, src/service/flex-service.ts, src/service/project-group-service.ts, test/unit/flex.service.test.ts, test/unit/project-group.service.test.ts
Task: https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1465/
- Duplicate name error handling message refactor for service and project group.
- Unit test coverage.
=> Deactive service/pg error message handling

src/controller/user-management-controller.ts, src/model/dto/register-user-dto.ts, src/model/dto/reset-credentials-dto.ts
Task:
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1168
-Added updated password policy regex validation
=> Password policy update

README.md, src/service/user-management-service.ts
Task: https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1168/
Error handling from Authz model error on registration.
=> Registration model Error handling 

src/assets/user-management-spec.json, src/controller/user-management-controller.ts, src/model/dto/register-user-dto.ts, src/service/interface/user-management-interface.ts, src/service/user-management-service.ts, test/controller/user-management.controller.test.ts, test/unit/user-management.service.test.ts
Task: 
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1701/
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1710/
- Added functionality for admin to download the tdei users as csv with Name, email , roles
- Enhanced get user project groups with project group search filter
- Updated user management specification
- Enhanced unit test cases
=> Task 1701 , 1710

src/controller/project-group-controller.ts, src/model/dto/roles-req-dto.ts
- Adding the restriction for project group roles for Admin and POC only
- Removing validation decorator for roles property, given it can be empty if we need to remove user from the project group
=> Feature 1504

db-management/migrations/20250214074240-tdei-user-role-deletion.js, db-management/migrations/sqls/20240430101231-init-up.sql, db-management/migrations/sqls/20250214074240-tdei-user-role-deletion-down.sql, db-management/migrations/sqls/20250214074240-tdei-user-role-deletion-up.sql, src/constants/role-id-constants.ts
- Removing the legacy 'tdei_user' role from users if any assigned. 
- Deleting the 'tdei_user' role from system
=> Removing tdei_user role from system as it is replaced by member role

src/controller/user-management-controller.ts
Hot Fix - Fixing default page size to 20 if page size is less than 20
=> Hotfix: Default page size to 20

src/assets/user-management-spec.json, src/controller/project-group-controller.ts, src/model/dto/dataset-viewer-dto.ts, src/model/params/project-group-get-query-params.ts
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/2218/
- data_viewer_allowed filter for project group
- Changed the validation logic for dataviewer preference dto
- Verify update dat viewer preference working
- Verify data_viewer_allowed filter working on project group
=> data_viewer_allowed filter for project group

src/assets/user-management-spec.json, src/model/dto/project-group-role-dto.ts, src/service/user-management-service.ts
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/2218/
- Update project group roles to include data viewer config information
- Updated spec accordingly
- Test the Get project group roles api to verify data viewer config information is present
=> Feature 2228

src/model/params/project-group-get-query-params.ts
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/2218
- Added space for query compose; initially there was no space and query was failing to execute. 
- Test get project api
=> added space for query composition

src/service/user-management-service.ts, test/unit/user-management.service.test.ts
https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/2389
- Handled no expiry promo code case
- Test Register user with no expiry promo code
=> handle no expiry case
